--Atividade 03/08

-- 1)
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID FROM HR.EMPLOYEES 
WHERE SALARY > 500
ORDER BY EMPLOYEE_ID;

-- 2)
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME FROM HR.EMPLOYEES
WHERE LAST_NAME NOT LIKE '%E%'
AND LAST_NAME NOT LIKE '%e%';

-- 3)
SELECT JOB_ID, JOB_TITLE FROM HR.JOBS
WHERE JOB_TITLE LIKE '%Sales%'
AND MIN_SALARY > 6000;

-- 4)
SELECT * FROM HR.DEPARTMENTS
WHERE DEPARTMENT_NAME LIKE '%Marketing%';

SELECT  FIRST_NAME FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID LIKE '%20%';

-- 5)
SELECT DEPARTMENT_NAME, LOCATION_ID  FROM HR.DEPARTMENTS
WHERE MANAGER_ID IS NULL
ORDER BY DEPARTMENT_NAME, LOCATION_ID;

-- 6)
SELECT DISTINCT LOCATION_ID FROM HR.DEPARTMENTS 
ORDER BY LOCATION_ID;

-- 7)
SELECT * FROM HR.DEPARTMENTS
WHERE DEPARTMENT_NAME LIKE 'Sales';

SELECT FIRST_NAME, LAST_NAME, SALARY, (SALARY * COMMISSION_PCT) FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID LIKE '%80%'
ORDER BY FIRST_NAME, SALARY;

-- 8)
SELECT FIRST_NAME, LAST_NAME FROM HR.EMPLOYEES
WHERE FIRST_NAME LIKE '%Alex%' OR LAST_NAME LIKE '%Alex%';

-- 9)
SELECT FIRST_NAME , LAST_NAME, SALARY, MANAGER_ID 
FROM HR.EMPLOYEES





